---
- name: Restart prometheus
  systemd:
    name: docker-compose-service@prometheus
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Reaload prometheus
  community.docker.docker_container_exec:
    container: prometheus
    command: killall -HUP prometheus